language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
    - php: 7.2
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini;

install:
  - composer install -a --no-dev

script:
  - |
    # Vendors list
    php vendor/bin/phpbench vendors

  - |
    # Performing serialization benchmark
    php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=serialize --iterations=10

  - |
    # Performing deserialization benchmark
    php vendor/bin/phpbench run --warmup=1 --report=tsantos --group=deserialize --iterations=10
