language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
  fast_finish: true

install:
  - composer install -a --no-dev

script:
  - php app vendors
  - php app serialize -s 100 -b 100
  - php app deserialize -s 100 -b 100
